version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: your-backend-image
    ports:
      - "${BACKEND_PORT:-5000}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ConnectionStrings__DefaultConnection=${DefaultConnection}
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: your-frontend-image
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "${SQLSERVER_DB}"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Om du har initialiseringsskript

volumes:
  sqlserverdata:
