# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - App-examensarbete-optimerad

on:
  push:
    branches:
      - optimerad
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Package dist
        run: |
          cd frontend/dist
          zip -r release.zip .
      - name: Upload release.zip
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: frontend/dist/release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release.zip
        uses: actions/download-artifact@v4
        with:
          name: release-zip

      - name: Debug — lista rotmappen
        run: ls -la .

      - name: Deploy to Azure (clean)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_OPTIMERAD }}
          package: "./release.zip"
          clean: true
